controllers/GruposusuariosController.php
<?php

namespace app\controllers;

use Yii;
use stdClass;
use yii\web\Response;
use yii\web\Controller;
use app\models\Usuarios;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use app\models\GruposDctUsuarios;

class GruposusuariosController extends Controller{

    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action) {
        
        if ($this->action->id == "error"){
            return $this->render('error');
        }

        if ($action->actionMethod == "actionGetgruposporusuario" ) { 
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }


    public function init() {

        if (!isset(Yii::$app->session["nombreUsuario"])) {
            return $this->redirect(['/login']);
        }
    }


    public function actionCrear(){

        $session = Yii::$app->session;

        $model = new GruposDctUsuarios();

        if ((Yii::$app->request->isAjax) && ($model->load(Yii::$app->request->post()))) {
			
            Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}

        if ($_POST) {
            if (isset($_POST["GruposDctUsuarios"]["id_grupo_dct"]) && isset($_POST["GruposDctUsuarios"]["id_usuario"])) {
                if ($_POST["GruposDctUsuarios"]["id_usuario"] != "") {

                    $GruposDeUsuario = GruposDctUsuarios::find()->where(["id_usuario" => $_POST["GruposDctUsuarios"]["id_usuario"]])->all();

                    if (count($GruposDeUsuario) > 0) {
                        foreach ($GruposDeUsuario as $key => $value) {
                            $value->delete();
                        }
                    }

                    foreach ($_POST["GruposDctUsuarios"]["id_grupo_dct"] as $key => $value) {
                        $model = new GruposDctUsuarios();
                        $model->id_grupo_dct = $value;
                        $model->id_usuario = $_POST["GruposDctUsuarios"]["id_usuario"];
                        $model->save();
                    }
                }
            }   
            
            return $this->redirect(["crear"]);
        }

        $usuarios = ArrayHelper::map(Usuarios::find()->where(['<>','id', 1])->all(), 'id', 'usuario');

        $response = Yii::$app->runAction('dct/grupos', ["token" => $session['tokenDCT']]);

        $grupos = [];
        if (count($response) > 0) {
            foreach ($response as $key => $value) {
                $grupos[$value->id] = $value->name;
            }
        }
        
        return $this->render('crear', ["model" => $model, "usuarios" => $usuarios, "grupos" => $grupos]);
    }

    public function actionEditar($id){

        $session = Yii::$app->session;

        $model = new GruposDctUsuarios();

        if ((Yii::$app->request->isAjax) && ($model->load(Yii::$app->request->post()))) {
			
            Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}

        if ($_POST) {

            if (isset($_POST["GruposDctUsuarios"]["id_grupo_dct"])) {

                    $GruposDeUsuario = GruposDctUsuarios::find()->where(["id_usuario" => $id])->all();

                    if (count($GruposDeUsuario) > 0) {
                        foreach ($GruposDeUsuario as $key => $value) {
                            $value->delete();
                        }
                    }

                    foreach ($_POST["GruposDctUsuarios"]["id_grupo_dct"] as $key => $value) {
                        $model = new GruposDctUsuarios();
                        $model->id_grupo_dct = $value;
                        $model->id_usuario = $id;
                        $model->save();
                    }

            }   
            
            return $this->redirect(["lista"]);
        }

        $usuario = Usuarios::findOne($id);

        $response = Yii::$app->runAction('dct/grupos', ["token" => $session['tokenDCT']]);

        $grupos = [];
        if (count($response) > 0) {
            foreach ($response as $key => $value) {
                $grupos[$value->id] = $value->name;
            }
        }
        
        return $this->render('editar', ["model" => $model, "usuario" => $usuario, "grupos" => $grupos, "idUsuario" => $id]);
    }

    public function actionLista(){

        $db = Yii::$app->db;
        $sql = $db->createCommand("SELECT id_usuario, u.usuario, count(id_grupo_dct) as cantidad_grupos from grupos_dct_usuarios gu inner join usuarios u on gu.id_usuario = u.id
        group by id_usuario, u.usuario");

        $gruposusarios = $sql->queryAll();
        
        return $this->render('lista', ["gruposusarios" => $gruposusarios]);
    }
    
    public function actionGetgruposporusuario(){
        $res = array();
        if (isset($_POST["id"])) {
            $idUsuario = $_POST["id"];
            $gruposPorUsuario = GruposDctUsuarios::find()->where(["id_usuario" => $idUsuario ])->asArray()->all();
            if ($gruposPorUsuario!=false){
                foreach($gruposPorUsuario as $grupo){
                  $res[] = $grupo['id_grupo_dct']; 
                }
            }
        }
        return implode(',',$res);
    }

}

views/gruposusuarios/crear.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Agregar usuarios a grupo de DCT';
$bread1 = 'Grupos-Usuarios';
$bread2 = 'Lista de grupos-usuarios';
$bread3 = $this->title;
$this->params['activeLink'] = "grupousuario";
?>

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h2 class="page-title" style="font-size: 16px;"><?= $this->title ?></h2>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><?= $bread1 ?></li>
                <?php if ($bread2 != '') { ?>
                    <li class="breadcrumb-item">
                        <a href="<?= Yii::getAlias('@web'); ?>/gruposusuarios/lista"><?= $bread2 ?></a>
                    </li>
                <?php } ?>
                <?php if ($bread3 != '') { ?>
                    <li class="breadcrumb-item"><?= $bread3 ?></li>
                <?php } ?>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card-box">

            <?php
            $form = ActiveForm::begin([
                        'method' => 'post',
                        'id' => 'GrupoUsuarioForm',
                        'options' => [
                            'class' => 'form-horizontal',
                        ],
                        'enableClientValidation' => false,
                        'enableAjaxValidation' => true,
            ]);
            ?>
            
            <div style="padding-left:50px;">
                <div class="row">
                    <div id="" class="form-group col-md-3">
                        <?= $form->field($model, 'id_usuario')->dropdownList($usuarios, ['onchange'=>'getGruposPorUsuario(this.value);', 'class' => 'selectpicker form-control', 'data-live-search' => 'true', 'data-actions-box' => "true", 'prompt' => 'Seleccione', 'title' => "Usuarios"])->error(['style'=>'color:white', 'class' => 'help-block badge badge-danger']) ?>
                    </div>      
                </div>
                <div class="row">
                    <div id="drop_grupos_dct" class="form-group col-md-3" style="">
                        <?= $form->field($model, 'id_grupo_dct')->dropdownList($grupos, ['size'=>10, 'class' => 'selectpicker form-control', 'data-live-search' => 'true', 'title' => "Grupos DCT", "multiple" => "multiple"])->error(['style'=>'color:white', 'class' => 'help-block badge badge-danger']) ?>
                    </div>                          
                </div>


                <div class="row" style="padding-left:10px">
                    <div class="form-actions">
                        <?= Html::submitButton(Yii::t('app', '<i class="fa fa-check"></i> Guardar'), ['class' => 'btn btn-success waves-effect waves-light', 'id' => 'btn_guardar']) ?>
                    </div>
                </div>
            </div>

<?php $form->end(); ?>

        </div>
    </div>
</div>


<script type="text/javascript">
    
    function getGruposPorUsuario(id){
        // limpio los valores seleccionados antes
        $("#gruposdctusuarios-id_grupo_dct").val([]);
        if (id > 0){
            $.ajax({
                    type: "POST",
                    url: "<?php echo Yii::$app->request->baseUrl . '/gruposusuarios/getgruposporusuario'; ?>",
                    dataType: "html",
                    data: {id: id},
                    success: function (response) {
                        // console.log(response);
                        $("#gruposdctusuarios-id_grupo_dct").val([response]);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert("Problemas enviado datos : \n" + xhr.responseText);
                    }
                });
        }
    }
    
    $("#patente_div, #header_listado").remove();

</script>



views/gruposusuarios/editar.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Editar grupos DCT en usuario <b>' . $usuario->usuario . '</b>';
$bread1 = 'Grupos-Usuarios';
$bread2 = 'Lista de grupos-usuarios';
$bread3 = $this->title;
$this->params['activeLink'] = "grupousuario";
?>

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h2 class="page-title" style="font-size: 16px;"><?= $this->title ?></h2>

            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><?= $bread1 ?></li>
<?php if ($bread2 != '') { ?>
                    <li class="breadcrumb-item">
                        <a href="<?= Yii::getAlias('@web'); ?>/gruposusuarios/lista"><?= $bread2 ?></a>
                    </li>
                <?php } ?>
                <?php if ($bread3 != '') { ?>
                    <li class="breadcrumb-item"><?= $bread3 ?></li>
<?php } ?>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card-box">

            <?php
            $form = ActiveForm::begin([
                        'method' => 'post',
                        'id' => 'GrupoUsuarioForm',
                        'options' => [
                            'class' => 'form-horizontal',
                        ],
                        'enableClientValidation' => false,
                        'enableAjaxValidation' => true,
            ]);
            ?>
            <div style="padding-left:50px;">    
                <div class="row">

                    <div id="" class="form-group col-md-3">
                        <label for="">Usuario a editar</label>
                        <input type="text" class="form-control" readonly value="<?= $usuario->usuario ?>">
                    </div>   
                </div>
                <div class="row">
                    <div id="drop_grupos_dct" class="form-group col-md-3">
                        <?= $form->field($model, 'id_grupo_dct')->dropdownList($grupos, ['size'=>10, 'class' => 'selectpicker form-control', 'data-live-search' => 'true', 'title' => "Grupos DCT", "multiple" => "multiple"])->error(['class' => 'help-block badge badge-danger']) ?>
                    </div>                          
                </div>


                <div class="row" style="padding-left:10px">

                    <div class="form-actions">
                        <?= Html::submitButton(Yii::t('app', '<i class="fa fa-check"></i> Actualizar Grupos'), ['class' => 'btn btn-success waves-effect waves-light', 'id' => 'btn_guardar']) ?>
                    </div>

                </div>
            </div>

<?php $form->end(); ?>

        </div>
    </div>
</div>


<script type="text/javascript">

    function getGruposPorUsuario(id) {
        // limpio los valores seleccionados antes
        $("#gruposdctusuarios-id_grupo_dct").val([]);
        if (id > 0) {
            $.ajax({
                type: "POST",
                url: "<?php echo Yii::$app->request->baseUrl . '/gruposusuarios/getgruposporusuario'; ?>",
                dataType: "html",
                data: {id: id},
                success: function (response) {
                    // console.log(response);
                    $("#gruposdctusuarios-id_grupo_dct").val([response]);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert("Problemas enviado datos : \n" + xhr.responseText);
                }
            });
        }
    }

    $("#patente_div, #header_listado").remove();

    $(document).ready(function () {
        getGruposPorUsuario(<?= $idUsuario; ?>);
    });

</script>



views/gruposusuarios/lista.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

    $this->title = 'Listado de usuarios por grupos';
    $bread1  = 'Grupos-Usuarios';
    $bread2  = $this->title;
    $bread3  = '';
    $this->params['activeLink'] = "grupousuario";
?>

<!-- DataTables -->
<link href="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />

<!-- Responsive datatable examples -->
<link href="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />

<!-- scripts -->
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Buttons examples -->
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/buttons.bootstrap4.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/jszip.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/pdfmake.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/vfs_fonts.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/buttons.html5.min.js"></script>
<script src="<?= Yii::getAlias('@web'); ?>/content/admin/plugins/datatables/buttons.print.min.js"></script>


<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h2 class="page-title" style="font-size: 16px;"><?= $this->title ?></h2>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><?= $bread1 ?></li>
                <?php if ($bread2  != '') { ?>
                    <li class="breadcrumb-item">
                        <?= $bread2 ?>
                    </li>
                <?php } ?>
                <?php if ($bread3  != '') { ?>
                    <li class="breadcrumb-item"><?= $bread3 ?></li>
                <?php } ?>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-md-12">
        <div class="card-box table-responsive">
            <a href="<?= Yii::getAlias('@web'); ?>/gruposusuarios/crear"  class="btn btn-success waves-effect waves-light">Asociar usuario a grupo dct</a>
            <a href="<?= Yii::getAlias('@web'); ?>/usuarios/crear"  class="btn btn-success waves-effect waves-light">Crear usuario</a>

            <table id="responsive-datatable" class="table table-bordered table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>id usuario</th>
                        <th>Usuario</th>
                        <th width="50">cantidad de grupos</th>
                        <th width="20">Editar</th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($gruposusarios as $key => $value) { ?>
                        <tr>
                            <td><?= $value["id_usuario"] ?></td>
                            <td><?= $value["usuario"] ?></td>
                            <td><?= $value["cantidad_grupos"] ?></td>

                            <td class="text-center">

                                <a href="<?= Yii::getAlias('@web'); ?>/gruposusuarios/editar/<?= $value["id_usuario"]?>" class="btn btn-sm btn-primary"><i class="fal fa-edit" ></i></a>

                            </td>
                        </tr>
                    <?php } ?>
                </tbody>

            </table>

        </div>  
    </div>
</div>


<div class="modal fade" id="modalSensor" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar nombre</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?php $form = ActiveForm::begin([
                    'method' => 'post', 
                    'id'=> 'CrearUsuario', 
                    'action' => Url::to(['site/guardarnombresensor']),
                    'options'=> [
                        'class' => 'form-horizontal',
                    ], 
                    'enableClientValidation' => false,
                    'enableAjaxValidation' => true, 
                    ]); ?>
                        
                        <div class="row">

                            <div  class="form-group col-md-12">
                                <label for="st_name">Nombre del sensor</label>
                                <input class="form-control" type="text" name="st_name" id="st_name" required >
                                <input class="form-control" type="hidden" name="st_mac" id="st_mac" >
                            </div>

                        </div>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <?= Html::submitButton(Yii::t('app', '<i class="fa fa-check"></i> Guardar'), ['class' => 'btn btn-success waves-effect waves-light', 'id'=>'btn_guardar']) ?>
            </div>
            <?php $form->end(); ?>
        </div>
    </div>
</div>

<script type="text/javascript">

$(document).ready(function () {
    $('#responsive-datatable').DataTable({
        dom: 'Bfrtip',
        buttons: [  ],
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json",
            "sEmptyTable": "Sin datos para mostrar"
        },
        "columns": [
            { "width": "5%" },
            null,
            { "width": "10%" },
            { "width": "5%" },
        ],
    });
    
});

$("#patente_div, #header_listado").remove();

</script>
